[project]
name = "telephony-test-platform"
version = "0.1.0"
description = "A robust telephony testing platform for call flow management with Twilio integration"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "twilio>=9.4.6",
]
